files:
  sequences_file: '../biological_data_pfp/train/train.fasta'
  embeddings_file: '../biological_data_pfp/train/train_embeddings.h5'
  train_file: '../biological_data_pfp/train/train_set.tsv'
  infoprot_file: '../biological_data_pfp/train/train_protein2ipr.dat'
  train_ids_file: '../biological_data_pfp/train/train_ids.txt'

test_files:
  sequences_file: '../biological_data_pfp/test/test.fasta'
  embeddings_file: '../biological_data_pfp/test/test_embeddings.h5'
  infoprot_file: '../biological_data_pfp/test/test_protein2ipr.dat'
  test_ids_file: '../biological_data_pfp/test/test_ids.txt'

collection_name: 'sequence_embeddings'
neighbors: 5

ingestion:
  execute: false
  batch_size: 100
preprocessing:
  execute: true
  batch_size: 10
  out_rows: 150