test_files:
  embeddings_file: '../biological_data_pfp/test/test_embeddings.h5'
  test_ids_file: '../biological_data_pfp/test/test_ids.txt'

models:
  celullar_component_model: './model/cc_model.h5'
  biological_process_model: './model/bp_model.h5'
  molecular_function_model: './model/mf_model.h5'

frequency_table:
  cc_frequency_table: './dataset/train/cellular_component_freq.csv'
  mf_frequency_table: './dataset/train/molecular_function_freq.csv'
  bp_frequency_table: './dataset/train/biological_process_freq.csv'

output_file: './outputs/prediction.tsv'

ontology:
  train_dataset_path: '../biological_data_pfp/train/train_set.tsv'
  gene_ontology_path: '../biological_data_pfp/train/go-basic.obo'
